- title: Learning Machines
  description: We are infinitely curious of the world around us. Constantly challenging ourselves to acquire new knowledge and test our comfort zones. Happiness is finally figuring out how something works.
  icon: images/value-learning-machines.svg

- title: Never Give Up
  description: There is a solution to every problem. Our job is to persevere and outlast everyone else to find it every time. We embody the tenacity to succeed in whatever wedo. We are unstoppable.
  icon: images/value-never-give-up.svg

- title: We have each other's back
  description: Whatever happens, we are in this together. We treat each other the way we want to be treated. Collaborating and supporting one another to reach our potential.
  icon: images/value-have-back.svg

- title: Challenge the status quo
  description: We dare to be different. We continuously question the way things are done. Embracing change is part of who we are and what enables us to thrive.
  icon: images/value-status-quo.svg

- title: Do epic work
  description: We attract and nurture the most outstanding people in our industry. People who take responsibility for their work. Always striving to give their personal best in whatever they do.
  icon: images/value-epic-work.svg